### ISSUE TITLE
EthClient.Contract.get_functions/1 only works with etherscan connected chains

### ISSUE THREAD

**Issue by SantiagoPittella** [lambdaclass/ethereum_war_game_tooling#22]
If you try to call `EthClient.Contract.get_functions/1` with a contract address as parameter, the function will automatically try to search the functions from etherscan and will generate an error if the contract was deployed in the local node.
Error:
```
** (MatchError) no match of right hand side value: {:error, :unknown_chain_id_for_etherscan}
    (eth_client 0.1.0) lib/eth_client/abi.ex:12: EthClient.ABI.get_etherscan/1
    (eth_client 0.1.0) lib/eth_client/contract.ex:10: EthClient.Contract.get_functions/1
``` 
The functions works locally only if the parameter is the path to the ABI file.

**Comment by mfachal** [comment]
This might be of interest:
https://ethereum.stackexchange.com/questions/15603/web3-js-get-contract-abi-knowing-only-contract-address
https://docs.soliditylang.org/en/v0.8.13/metadata.html
